# app.py - Minimal Flask application for MedHub (DB Removed for Testing)

import os
from flask import Flask, render_template, request, redirect, url_for, flash, session
from flask_wtf.csrf import CSRFProtect
from werkzeug.security import generate_password_hash, check_password_hash
from dotenv import load_dotenv

# Load environment
load_dotenv()

app = Flask(__name__)
app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY', 'dev_secret_fallback')
app.config['WTF_CSRF_ENABLED'] = True

csrf = CSRFProtect(app)

# Mock users for testing (in-memory, not persistent)
MOCK_USERS = {
    'admin@example.com': {
            'password': generate_password_hash('adminpass'),
                    'role': 'admin',
                            'full_name': 'Admin User'
                                },
                                    'doctor@example.com': {
                                            'password': generate_password_hash('doctorpass'),
                                                    'role': 'doctor',
                                                            'full_name': 'Dr. Example'
                                                                },
                                                                    'patient@example.com': {
                                                                            'password': generate_password_hash('patientpass'),
                                                                                    'role': 'patient',
                                                                                            'full_name': 'Patient User'
                                                                                                }
                                                                                                }

                                                                                                # Routes (DB-dependent removed or mocked)

                                                                                                @app.route('/')
                                                                                                def index():
                                                                                                    return render_template('index.html')

                                                                                                    @app.route('/about')
                                                                                                    def about():
                                                                                                        return render_template('about.html')

                                                                                                        @app.route('/services')
                                                                                                        def services():
                                                                                                            return render_template('services.html')

                                                                                                            @app.route('/contact', methods=['GET', 'POST'])
                                                                                                            @csrf.exempt  # Mock CSRF for simplicity
                                                                                                            def contact():
                                                                                                                if request.method == 'POST':
                                                                                                                        name = request.form.get('name', '').strip()
                                                                                                                                email = request.form.get('email', '').strip()
                                                                                                                                        message = request.form.get('message', '').strip()
                                                                                                                                                if not all([name, email, message]):
                                                                                                                                                            flash('All fields are required.', 'danger')
                                                                                                                                                                        return render_template('contact.html')
                                                                                                                                                                                flash('Your message has been sent!', 'success')
                                                                                                                                                                                        return redirect(url_for('index'))
                                                                                                                                                                                            return render_template('contact.html')

                                                                                                                                                                                            @app.route('/register', methods=['GET', 'POST'])
                                                                                                                                                                                            def register():
                                                                                                                                                                                                if request.method == 'POST':
                                                                                                                                                                                                        email = request.form.get('email', '').strip().lower()
                                                                                                                                                                                                                password = request.form.get('password', '')
                                                                                                                                                                                                                        if not email or not password:
                                                                                                                                                                                                                                    flash('Email and password required.', 'danger')
                                                                                                                                                                                                                                                return render_template('register.html')
                                                                                                                                                                                                                                                        if email in MOCK_USERS:
                                                                                                                                                                                                                                                                    flash('Email already exists.', 'danger')
                                                                                                                                                                                                                                                                                return render_template('register.html')
                                                                                                                                                                                                                                                                                        # Mock registration (not saving)
                                                                                                                                                                                                                                                                                                flash('Registration successful! Use demo credentials to login.', 'success')
                                                                                                                                                                                                                                                                                                        return redirect(url_for('login'))
                                                                                                                                                                                                                                                                                                            return render_template('register.html')

                                                                                                                                                                                                                                                                                                            @app.route('/login', methods=['GET', 'POST'])
                                                                                                                                                                                                                                                                                                            def login():
                                                                                                                                                                                                                                                                                                                if request.method == 'POST':
                                                                                                                                                                                                                                                                                                                        email = request.form.get('email', '').strip().lower()
                                                                                                                                                                                                                                                                                                                                password = request.form.get('password', '')
                                                                                                                                                                                                                                                                                                                                        if not email or not password:
                                                                                                                                                                                                                                                                                                                                                    flash('Email and password required.', 'danger')
                                                                                                                                                                                                                                                                                                                                                                return render_template('login.html')
                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                user_data = MOCK_USERS.get(email)
                                                                                                                                                                                                                                                                                                                                                                                        if user_data and check_password_hash(user_data['password'], password):
                                                                                                                                                                                                                                                                                                                                                                                                    session['user_id'] = email
                                                                                                                                                                                                                                                                                                                                                                                                                session['role'] = user_data['role']
                                                                                                                                                                                                                                                                                                                                                                                                                            session['full_name'] = user_data['full_name']
                                                                                                                                                                                                                                                                                                                                                                                                                                        flash('Login successful!', 'success')
                                                                                                                                                                                                                                                                                                                                                                                                                                                    if user_data['role'] == 'admin':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return redirect(url_for('index'))  # Mock redirect
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                elif user_data['role'] == 'doctor':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return redirect(url_for('index'))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return redirect(url_for('index'))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    flash('Invalid email or password. Try: admin@example.com / adminpass', 'danger')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return render_template('login.html')

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @app.route('/logout')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def logout():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            session.clear()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                flash('Logged out successfully.', 'success')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return redirect(url_for('index'))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @app.route('/profile')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def profile():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if 'user_id' not in session:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                flash('Please log in.', 'danger')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return redirect(url_for('login'))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return render_template('profile.html', full_name=session.get('full_name', 'User'))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @app.route('/apply_doctor', methods=['GET', 'POST'])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def apply_doctor():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if request.method == 'POST':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        full_name = request.form.get('full_name', '').strip()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                email = request.form.get('email', '').strip().lower()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if not all([full_name, email]):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    flash('All fields required.', 'danger')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return render_template('apply_doctor.html')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        flash('Application submitted! (Mock)', 'success')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return redirect(url_for('index'))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return render_template('apply_doctor.html')

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Mock dashboard (no DB data)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @app.route('/patient/dashboard')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def patient_dashboard():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if session.get('role') != 'patient':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                flash('Access denied.', 'danger')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return redirect(url_for('index'))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return render_template('patient_dashboard.html', show_payment=True)  # Mock

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @app.route('/doctor/dashboard')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def doctor_dashboard():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if session.get('role') != 'doctor':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        flash('Access denied.', 'danger')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return redirect(url_for('index'))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return render_template('doctor_dashboard.html')  # Mock

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @app.route('/admin/dashboard')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def admin_dashboard():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if session.get('role') != 'admin':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                flash('Access denied.', 'danger')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return redirect(url_for('index'))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return render_template('admin_dashboard.html')  # Mock

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @app.route('/patient/payment', methods=['GET', 'POST'])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def payment():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if session.get('role') != 'patient':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        flash('Access denied.', 'danger')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return redirect(url_for('index'))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if request.method == 'POST':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            session['paid'] = True
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    flash('Payment successful! (Mock)', 'success')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return redirect(url_for('patient_dashboard'))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return render_template('payment.html')

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Error handlers
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                @app.errorhandler(404)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def not_found(error):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return render_template('404.html'), 404

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @app.errorhandler(500)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def internal_error(error):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return render_template('500.html'), 500

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if __name__ == '__main__':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            app.run(debug=False)